### ISSUE TITLE
Hit@10 is always 0.00%

### ISSUE THREAD

**Issue by JianLiu91** [zchYellow/TransE#1]
What's the result of mean rank and Hit@10 is your experiment?

**Comment by ZichaoHuang** [comment]
Sorry for taking so long.
I have rewrote the TransE model under this repo.
I get 125 of MeanRank and 52.5% of Hits@10 under the "Filter" setting after 60 epochs of training.
Feel free to ask any questions.

**Comment by sammua** [comment]
> Sorry for taking so long.
> I have rewrote the TransE model under this repo.
> I get 125 of MeanRank and 52.5% of Hits@10 under the "Filter" setting after 60 epochs of training.
> Feel free to ask any questions.

使用 wn18 的数据, epoch=60 其他默认 得到的 hit@10 还是0

**Comment by ZichaoHuang** [comment]
@sammua 可以提供下运行的.sh文件和输出的日志吗？

**Comment by sammua** [comment]
[Archive.zip](https://github.com/ZichaoHuang/TransE/files/2670135/Archive.zip)
你好, .sh文件和输出日志已经打包在 Archive.zip 了, 我只改了代码中的过程输出, 没有改代码逻辑.

**Comment by ZichaoHuang** [comment]
@sammua 有几点问题：
（1）你提供的train_wn18.sh中的参数设置跟此repo下的train_wn18.sh并不完全一样，margin跟embedding_size都不同，建议改成默认的参数再跑一次看看结果；
（2）我使用了你提供的train_wn18.sh（eval_freq改成了10），也没有发现问题，hits@10是正常的。你可以试试我在下面提供的train_wn18.sh再跑一次，对照我的log文件来看是否还是有问题；*
（3）请问你是在什么平台下运行的呢？

*（2）中输出的log文件和使用的.sh文件：
[log&sh.zip](https://github.com/ZichaoHuang/TransE/files/2670248/log.sh.zip)

**Comment by sammua** [comment]
[Archive 2.zip](https://github.com/ZichaoHuang/TransE/files/2670446/Archive.2.zip)
(1)(2)我使用了你的 .sh 运行了一遍, 得到的还是 0.000
(3) 我是在mac 下运行的, python2.7 (你的源码是python3的, 我改了些代码能run, 但是没有改代码逻辑)

**Comment by ZichaoHuang** [comment]
那应该是python版本的问题了，你试试用python3跑一下。2跟3不兼容，特别是涉及到生成器，很容易出问题。

**Comment by sammua** [comment]
> 那应该是python版本的问题了，你试试用python3跑一下。2跟3不兼容，特别是涉及到生成器，很容易出问题。

好的, 我之后用3试一下, 谢谢!

**Comment by hljjjmssyh** [comment]
你好！我想问一下您还在关注TransE 我在用pytorch实现TransR的时候，准确率出现了问题，想请求您的帮助

**Comment by ZichaoHuang** [comment]
@hljjjmssyh TransR需要用TransE的结果做初始化，否则收敛比较慢。有问题可以直接去TransR的repo下提issue。

**Comment by hljjjmssyh** [comment]
> @hljjjmssyh TransR需要用TransE的结果做初始化，否则收敛比较慢。有问题可以直接去TransR的repo下提issue。

好的，TransR的repo 是指THU的repo嘛？可以加一下您的邮箱吗？方便探讨，谢谢你的指导

**Comment by ZichaoHuang** [comment]
是THU的repo。
我没复现过TransR，应该也帮不上什么忙，有问题直接在那边的issue问吧。
这个issue的讨论有点偏题了，我先关了，跟这个repo有关的其他问题可以随时提issue，我会尽快回复的。
