### ISSUE TITLE
embedding结果与entity、relation是如何对应的

### ISSUE THREAD

**Issue by Wangwxy** [zchYellow/TransE#10]
您好。请问，我把得到的embedding打印出来，这些embedding与entity、relation的对应关系是怎样的？

**Comment by ZichaoHuang** [comment]
`entity2id.txt`和`relation2id.txt`两个文件分别是实体和关系所对应的index，也就是embedding中对应的index。

**Comment by Wangwxy** [comment]
谢谢您。您的意思，就entity来说，是打印出的embedding的顺序就是entity2id.txt中的entity的顺序吗? 我现在只能打印出来embedding，不能把相应的id打印出来。所以有这个疑问。

**Comment by ZichaoHuang** [comment]
是的。
`entity2id.txt`和`relation2id.txt`实际上只是从0开始的index映射，而`self.entity_embedding`实际上可以看作是一个n*k的矩阵，n是实体的个数，k是实体embedding的维度，`self.entity_embedding`的第0行对应的就是index为0的实体的embedding。
`self.relation_embedding`也同理。

**Comment by Wangwxy** [comment]
谢谢！
