### ISSUE TITLE
The result is too good to make me feel confused

### ISSUE THREAD

**Issue by ghost** [zchYellow/TransE#12]
I set embedding size =300, margin=4, epoch =2000, and I got the following result :
188.4303 | 52.74941 | 0.518122 | 0.815788

It is too good. This version of TransE can beat most of the TransE-based methods. Why?

![image](https://user-images.githubusercontent.com/15712601/48040502-266f6e80-e1b4-11e8-895e-cbce9cf9bdd4.png)

And, your code is important to me, thanks!

**Comment by ZichaoHuang** [comment]
From my point of view, the original TransE results (from Bordes's paper in NIPS 2013) are way below its true performance.
Plus, the results shown in this repo are also not optimized. You can do a grid search to see how far it can get if you like.
Feel free to ask any questions when checking the code.

**Comment by ghost** [comment]
Thanks for your patience!
