### ISSUE TITLE
a question about hit@1 

### ISSUE THREAD

**Issue by ghost** [zchYellow/TransE#13]
I run your code and print the result about hit@1, hit@3 and hit@10. It is so strange that your hit@1 is lower than other TransE. In KB2E, the raw hit@1 is 0.168069, and the filter hit@1 is 0.364274. The results in this code are 0.04 and 0.12. (The hyperparameters will not change the range.)
Thanks for your code and patience~   :)

**Comment by ZichaoHuang** [comment]
KB2E is a pure handcrafted C++ implementation while this repo is a TensorFlow implementation of TransE. 
I am sorry that I can't give a specific reason which leads to this issue, but internal details like embedding initialization or optimization may somehow affect the final performance.

**Comment by ghost** [comment]
Thanks! You are very kind~
