### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by pingcx** [zchYellow/TransE#17]
作者您好！我想问您一下您的TransE代码中model.py中的n_generator，n_rank_calculator和ckpt_dir分别表示什么意思

**Comment by ZichaoHuang** [comment]
n_generator是生成数据时用到的最大进程数；n_rank_calculator是evaluation的时候算排名时用到的最大进程数，ckpt_dir是保存checkpoint文件的路径

**Comment by pingcx** [comment]
非常感谢您的回复！



我还有一些问题想问您,因为网上查一些关于multiprocessing的资料没弄清楚



我想弄清楚model.py文件中的launch_training函数中的三个循环的执行顺序以及它们中间运行的结果
for _ in range(self.n_generator), 



for raw_batch in self.kg.next_raw_batch(self.batch_size), 



for _ in range(self.n_generator)

，或者说为什么您这样写可以保证代码的有效执行，我可以参考什么资料并找到吗？



谢谢

**Comment by ZichaoHuang** [comment]
这个repo用到的多进程模型是最简单的生产者-消费者模型，你可以参考一下
