### ISSUE TITLE
filtering results

### ISSUE THREAD

**Issue by panda0881** [zchYellow/TransE#2]
Hi there, thank you so much for your work, it is very helpful. But I just have a small question about your code. It seems like you didn't apply filter results(removing all the other correct entity from the ranking) in the evaluation part. Is that correct?

This may have a huge impact on the final result.

Hongming

**Comment by ZichaoHuang** [comment]
Sorry for taking so long.
I have rewrote the TransE model and add the "Filter" setting for evaluation.
Note that the evaluation may take nearly an hour, depending on your server hardware.
Training is quite fast though(~20s/epoch, depending on your server hardware).
Feel free to ask any questions.
