### ISSUE TITLE
Compute Head and Tail Prediction on FB15K dataset

### ISSUE THREAD

**Issue by MuhibKhan** [zchYellow/TransE#20]
I want to check the Prediction Head and Tail Predictions at (Hits@10) on different types of relation like 1-to-1, 1-to-N, N-to-1 and N-to-N of TransE model like the results mentioned in the paper. How can I perform the Head and Tail Prediction on 1-to-1, 1-to-N, N-to-1 and N-to-N of relations of FB15k dataset?

**Comment by ZichaoHuang** [comment]
@MuhibKhan This repo does not implement the "detailed entity prediction" from the original paper, sorry about that.
