### ISSUE TITLE
您好，我用了您的代码跑我自己的数据集，为什么我的头实体预测的hit10很低，关系预测结果正常，请问是什么原因？

### ISSUE THREAD

**Issue by azhe1234** [zchYellow/TransE#22]
![image](https://user-images.githubusercontent.com/72532237/161372441-edbbadb7-aefc-4462-a76f-bc1d5b0c7756.png)

**Comment by ZichaoHuang** [comment]
一般来说，关系预测会比实体预测容易很多，所以关系预测的性能一般会比实体预测要高不少。
由于你用了自己的数据集，我不清楚你的数据集复杂程度怎样，所以很难给出建议。
不过一般实体预测的精度低都是一对多映射导致的，比如头实体预测精度低，一个可能的原因是数据集中存在多个头实体对应同一个关系映射到同一个或少数几个尾实体上。

**Comment by azhe1234** [comment]
> 一般来说，关系预测会比实体预测容易很多，所以关系预测的性能一般会比实体预测要高不少。 由于你用了自己的数据集，我不清楚你的数据集复杂程度怎样，所以很难给出建议。 不过一般实体预测的精度低都是一对多映射导致的，比如头实体预测精度低，一个可能的原因是数据集中存在多个头实体对应同一个关系映射到同一个或少数几个尾实体上。

那是要使用TransH训练这个模型吗？我的数据如下，包含很多一对多的数据，还有很多多对一的，还有例如带括号的那些分店信息
![image](https://user-images.githubusercontent.com/72532237/192765599-d53283ee-1558-409c-95bb-2879f23d42c6.png)
