### ISSUE TITLE
请问能给出输入数据的形式吗？

### ISSUE THREAD

**Issue by sjtuxcx** [zchYellow/TransE#7]

**Comment by ZichaoHuang** [comment]
输入数据需要包括：
1. entity2id.txt，该文件是实体集中每个实体到其id的映射表；
2. relation2id.txt，该文件是关系集中每个关系到其id的映射表；
3. train.txt文件，该文件是训练集三元组；
4. valid.txt文件，该文件是验证集三元组；
5. test.txt文件，该文件是测试集三元组。

具体的文件格式可以参考[这个repo](https://github.com/thunlp/KB2E)中的[data.zip](https://github.com/thunlp/KB2E/blob/master/data.zip)文件，里面包含了FB15k数据集以及WN18数据集。
每个数据集都最少需要包含上述的5个文件。
